CREATE OR REPLACE WAREHOUSE MARKETING_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

CREATE OR REPLACE WAREHOUSE FINANCE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;

CREATE OR REPLACE WAREHOUSE ETL_WH
WITH WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE;



CREATE OR REPLACE ROLE MARKETING_ANALYST;

CREATE OR REPLACE ROLE FINANCE_USER;

CREATE OR REPLACE ROLE ETL_DEVELOPER;


GRANT USAGE ON WAREHOUSE MARKETING_WH
TO ROLE MARKETING_ANALYST;

GRANT USAGE ON WAREHOUSE FINANCE_WH
TO ROLE FINANCE_USER;

GRANT USAGE ON WAREHOUSE ETL_WH
TO ROLE ETL_DEVELOPER;




CREATE OR REPLACE USER MKT_USER1
PASSWORD = 'Mkt@123'
LOGIN_NAME = 'MKT_USER1'
DEFAULT_ROLE = 'MARKETING_ANALYST'
DEFAULT_WAREHOUSE = 'MARKETING_WH'
MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER FIN_USER1
PASSWORD = 'Fin@123'
LOGIN_NAME = 'FIN_USER1'
DEFAULT_ROLE = 'FINANCE_USER'
DEFAULT_WAREHOUSE = 'FINANCE_WH'
MUST_CHANGE_PASSWORD = FALSE;

CREATE OR REPLACE USER ETL_USER1
PASSWORD = 'Etl@123'
LOGIN_NAME = 'ETL_USER1'
DEFAULT_ROLE = 'ETL_DEVELOPER'
DEFAULT_WAREHOUSE = 'ETL_WH'
MUST_CHANGE_PASSWORD = FALSE;


GRANT ROLE MARKETING_ANALYST TO USER MKT_USER1;

GRANT ROLE FINANCE_USER TO USER FIN_USER1;

GRANT ROLE ETL_DEVELOPER TO USER ETL_USER1;




CREATE OR REPLACE DATABASE RETAIL_MARKETING_DB;


CREATE OR REPLACE TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES AS
SELECT
    ss.ss_customer_sk AS customer_id,
    c.c_first_name AS first_name,
    c.c_last_name AS last_name,
    c.c_birth_year AS birth_year,

    i.i_item_sk AS item_id,
    i.i_product_name AS item_name,
    i.i_brand AS item_brand,
    i.i_class AS category,

    ss.ss_quantity AS quantity_sold,
    ss.ss_sales_price AS sales_price,
    ss.ss_net_paid AS amount_spent,

    d.d_date AS sale_date,
    d.d_year AS sale_year,
    d.d_moy AS sale_month

FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.STORE_SALES ss

JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.CUSTOMER c
ON ss.ss_customer_sk = c.c_customer_sk

JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.ITEM i
ON ss.ss_item_sk = i.i_item_sk

JOIN SNOWFLAKE_SAMPLE_DATA.TPCDS_SF10TCL.DATE_DIM d
ON ss.ss_sold_date_sk = d.d_date_sk
LIMIT 100000;


SELECT * 
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
LIMIT 20;


GRANT USAGE ON DATABASE RETAIL_MARKETING_DB
TO ROLE MARKETING_ANALYST;

GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC
TO ROLE MARKETING_ANALYST;

GRANT SELECT ON TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
TO ROLE MARKETING_ANALYST;


GRANT USAGE ON DATABASE RETAIL_MARKETING_DB
TO ROLE FINANCE_USER;

GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC
TO ROLE FINANCE_USER;

GRANT SELECT ON TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
TO ROLE FINANCE_USER;



GRANT USAGE ON DATABASE RETAIL_MARKETING_DB
TO ROLE ETL_DEVELOPER;

GRANT USAGE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC
TO ROLE ETL_DEVELOPER;

GRANT CREATE TABLE ON SCHEMA RETAIL_MARKETING_DB.PUBLIC
TO ROLE ETL_DEVELOPER;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA RETAIL_MARKETING_DB.PUBLIC
TO ROLE ETL_DEVELOPER;


ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'XSMALL';

SELECT
    sale_year,
    category,
    SUM(quantity_sold) AS total_quantity_sold,
    SUM(amount_spent) AS total_amount
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
GROUP BY sale_year, category
ORDER BY sale_year, total_quantity_sold;


USE WAREHOUSE MARKETING_WH;


ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'SMALL';



ALTER WAREHOUSE MARKETING_WH
SET WAREHOUSE_SIZE = 'XSMALL';


SELECT *
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
WHERE category <> 'optics';


SELECT *
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
WHERE sale_date BETWEEN '2000-01-01'
AND '2020-01-31';



ALTER TABLE RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
CLUSTER BY (sale_date);


SELECT *
FROM RETAIL_MARKETING_DB.PUBLIC.CAMPAIGN_SALES
WHERE sale_date BETWEEN '2000-01-01'
AND '2020-01-31';