CREATE OR REPLACE DATABASE RETAIL_DB;
CREATE OR REPLACE SCHEMA RETAIL_DB.ORDERS_DEMO;


CREATE OR REPLACE WAREHOUSE RETAIL_LOAD_WH
WITH
WAREHOUSE_SIZE='XSMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

USE WAREHOUSE RETAIL_LOAD_WH;

CREATE OR REPLACE ROLE RETAIL_DATA_ENGINEER_ROLE;

CREATE OR REPLACE USER RETAIL_ENGINEER_USER
PASSWORD="Retail@12345"
LOGIN_NAME="RETAIL ENGINEER USER"
FIRST_NAME="REUSER"
LAST_NAME="USER"
EMAIL="retail@example.com"
MUST_CHANGE_PASSWORD=FALSE
DEFAULT_WAREHOUSE=RETAIL_LOAD_WH;

SHOW USERS;

GRANT ROLE RETAIL_DATA_ENGINEER_ROLE TO USER RETAIL_ENGINEER_USER;

GRANT USAGE ON WAREHOUSE RETAIL_LOAD_WH TO ROLE RETAIL_DATA_ENGINEER_ROLE;

GRANT USAGE ON DATABASE RETAIL_DB TO ROLE RETAIL_DATA_ENGINEER_ROLE;

GRANT USAGE ON SCHEMA RETAIL_DB.ORDERS_DEMO TO ROLE RETAIL_DATA_ENGINEER_ROLE;


-- CREATE OR REPLACE STORAGE INTEGRATION azure_snowpipe_integration
-- TYPE = EXTERNAL_STAGE
-- STORAGE_PROVIDER = AZURE
-- ENABLED = TRUE
-- AZURE_TENANT_ID = 'your-tenant-id'
-- STORAGE_ALLOWED_LOCATIONS = (
-- 'azure://adls618.blob.core.windows.net/adls618'
-- );

-- DESC STORAGE INTEGRATION azure_snowpipe_integration;

CREATE OR REPLACE FILE FORMAT RETAIL_DB.ORDERS_DEMO.fileformat_azure
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 1;


-- CREATE OR REPLACE STAGE snowpipe.public.stage_azure
-- STORAGE_INTEGRATION = azure_snowpipe_integration
-- URL = 'azure://adls618.blob.core.windows.net/snowflakecsv'
-- FILE_FORMAT = fileformat_azure;


CREATE OR REPLACE STAGE RETAIL_DB.ORDERS_DEMO.STAGE_AZURE
URL='azure://adls618.blob.core.windows.net/retail-data/raw/orders'
CREDENTIALS=(
    AZURE_SAS_TOKEN='sp=racwl&st=2026-05-26T13:06:49Z&se=2026-05-26T21:21:49Z&sv=2026-02-06&sr=c&sig=VgOZL9wjONwKW8RQ2%2BnRP1uh5X8DgUhTSsYMsL0zWxU%3D'
)
FILE_FORMAT = RETAIL_DB.ORDERS_DEMO.fileformat_azure;


LIST @RETAIL_DB.ORDERS_DEMO.STAGE_AZURE;


CREATE OR REPLACE TABLE RETAIL_DB.ORDERS_DEMO.ORDERS_RAW (
    ORDER_ID INT, 
    CUSTOMER_ID VARCHAR(50), 
    PRODUCT_ID VARCHAR(50), 
    PRODUCT_NAME VARCHAR(50) , 
    CATEGORY VARCHAR(50),
    QUANTITY INT,
    UNIT_PRICE INT,
    ORDER_DATE DATE,
    CITY VARCHAR(50)
);


COPY INTO RETAIL_DB.ORDERS_DEMO.ORDERS_RAW 
FROM @RETAIL_DB.ORDERS_DEMO.STAGE_AZURE
FILE_FORMAT = RETAIL_DB.ORDERS_DEMO.fileformat_azure 
PATTERN = '.*\.csv'
ON_ERROR = 'CONTINUE';


SELECT * FROM RETAIL_DB.ORDERS_DEMO.ORDERS_RAW
order  by  order_id asc;

CREATE OR REPLACE TABLE RETAIL_DB.ORDERS_DEMO.ORDERS_FINAL (
    ORDER_ID INT, 
    CUSTOMER_ID VARCHAR(50), 
    PRODUCT_ID VARCHAR(50), 
    PRODUCT_NAME VARCHAR(50) , 
    CATEGORY VARCHAR(50),
    QUANTITY INT,
    UNIT_PRICE INT,
    ORDER_DATE DATE,
    CITY VARCHAR(50)
);


INSERT INTO RETAIL_DB.ORDERS_DEMO.ORDERS_FINAL
SELECT * FROM RETAIL_DB.ORDERS_DEMO.ORDERS_RAW;

SELECT * FROM RETAIL_DB.ORDERS_DEMO.ORDERS_FINAL;

CREATE OR REPLACE PIPE RETAIL_DB.ORDERS_DEMO.ORDERS_PIPE AS
COPY INTO RETAIL_DB.ORDERS_DEMO.ORDERS_RAW
FROM @RETAIL_DB.ORDERS_DEMO.STAGE_AZURE
FILE_FORMAT = (
    FORMAT_NAME = RETAIL_DB.ORDERS_DEMO.FILEFORMAT_AZURE
)
ON_ERROR = 'CONTINUE';

ALTER PIPE RETAIL_DB.ORDERS_DEMO.ORDERS_PIPE REFRESH;


CREATE OR REPLACE STREAM RETAIL_DB.ORDERS_DEMO.ORDERS_RAW_STREAM
ON TABLE RETAIL_DB.ORDERS_DEMO.ORDERS_RAW;

SHOW STREAMS IN SCHEMA RETAIL_DB.ORDERS_DEMO;


SELECT *
FROM RETAIL_DB.ORDERS_DEMO.ORDERS_RAW_STREAM;

CREATE OR REPLACE TASK RETAIL_DB.ORDERS_DEMO.MERGE_ORDERS_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('RETAIL_DB.ORDERS_DEMO.ORDERS_RAW_STREAM')
AS
MERGE INTO RETAIL_DB.ORDERS_DEMO.ORDERS_FINAL T
USING (
    SELECT *
    FROM RETAIL_DB.ORDERS_DEMO.ORDERS_RAW_STREAM
) S
ON T.ORDER_ID = S.ORDER_ID
WHEN MATCHED THEN
    UPDATE SET
        CUSTOMER_ID = S.CUSTOMER_ID,
        PRODUCT_ID = S.PRODUCT_ID,
        PRODUCT_NAME = S.PRODUCT_NAME,
        CATEGORY = S.CATEGORY,
        QUANTITY = S.QUANTITY,
        UNIT_PRICE = S.UNIT_PRICE,
        ORDER_DATE = S.ORDER_DATE,
        CITY = S.CITY
WHEN NOT MATCHED THEN
    INSERT (
        ORDER_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        PRODUCT_NAME,
        CATEGORY,
        QUANTITY,
        UNIT_PRICE,
        ORDER_DATE,
        CITY
    )
    VALUES (
        S.ORDER_ID,
        S.CUSTOMER_ID,
        S.PRODUCT_ID,
        S.PRODUCT_NAME,
        S.CATEGORY,
        S.QUANTITY,
        S.UNIT_PRICE,
        S.ORDER_DATE,
        S.CITY
    );


ALTER TASK RETAIL_DB.ORDERS_DEMO.MERGE_ORDERS_TASK RESUME;

SHOW TASKS IN SCHEMA RETAIL_DB.ORDERS_DEMO;


SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'MERGE_ORDERS_TASK'
    )
);


