-- Task 1: Create Database

CREATE OR REPLACE TRANSIENT DATABASE STREAMS_DB;


-- Task 2: Create Raw Sales Staging Table
CREATE OR REPLACE TABLE STREAMS_DB.PUBLIC.SALES_RAW_STAGING (
    ID INT, 
    PRODUCT STRING ,
    PRICE DECIMAL(10,2),
    AMOUNT INT , 
    STORE_ID INT 
);

-- Task 3: Insert Initial Sales Data

INSERT INTO STREAMS_DB.PUBLIC.SALES_RAW_STAGING
VALUES
    (1, 'Banana' , 1.99 , 1 , 1),
    (2, 'Lemon' , 0.99 , 1 , 1),
    (3, 'Apple' , 1.79 , 1 , 2),
    (4, 'Orange Juice' , 1.89 , 1 , 1),
    (5, 'Cereals' , 5.98 , 2 , 1);


SELECT * FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING;


-- Task 4: Create Store Table

CREATE OR REPLACE TABLE STREAMS_DB.PUBLIC.STORE_TABLE (
    STORE_ID INT, 
    LOCATION STRING, 
    EMPLOYEES INT 
);


-- Task 5: Insert Store Data

INSERT INTO STREAMS_DB.PUBLIC.STORE_TABLE
VALUES 
    (1, 'Chicago' , 33),
    (2, 'London' , 12);

SELECT * FROM  STREAMS_DB.PUBLIC.STORE_TABLE;

-- Task 6: Create Final Sales Table

CREATE OR REPLACE TABLE STREAMS_DB.PUBLIC.SALES_FINAL_TABLE (
    ID INT, 
    PRODUCT STRING ,
    PRICE DECIMAL(10,2),
    AMOUNT INT , 
    STORE_ID INT ,
    LOCATION STRING, 
    EMPLOYEES INT
);

-- Task 7: Perform Initial Full Load

INSERT INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE  
    (SELECT 
        SR.ID, SR.PRODUCT , SR.PRICE, SR.AMOUNT, SR.STORE_ID ,ST.LOCATION , ST.EMPLOYEES
    FROM STREAMS_DB.PUBLIC.SALES_RAW_STAGING AS SR
    INNER JOIN STREAMS_DB.PUBLIC.STORE_TABLE AS ST
    ON SR.STORE_ID = ST.STORE_ID
    ORDER BY SR.ID ASC);

-- Task 8: Verify Initial Load

-- Display data from:

-- SALES_RAW_STAGING;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_RAW_STAGING;
-- STORE_TABLE;
SELECT * FROM  STREAMS_DB.PUBLIC.STORE_TABLE;
-- SALES_FINAL_TABLE;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;



-- Stream Implementation
-- Task 9: Create Stream Object

CREATE OR REPLACE STREAM STREAMS_DB.PUBLIC.SALES_STREAM
ON TABLE STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

-- Task 10: View Stream Information

-- Execute commands to:

-- Show all streams.

SHOW STREAMS;


-- Describe the SALES_STREAM.
Describe STREAM STREAMS_DB.PUBLIC.SALES_STREAM;


-- Select data from SALES_STREAM.
SELECT * 
FROM STREAMS_DB.PUBLIC.SALES_STREAM;

-- Task 11: Insert New Sales Records

INSERT INTO STREAMS_DB.PUBLIC.SALES_RAW_STAGING
VALUES 
    (6 , 'Mango', 1.99 , 1, 2),
    (7 , 'Garlic' , 0.99 , 1, 1);

-- Task 12: Check Stream Data

SELECT * 
FROM STREAMS_DB.PUBLIC.SALES_STREAM;

-- Task 13: Verify Source and Target Tables

-- SALES_RAW_STAGING;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

-- SALES_FINAL_TABLE;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_FINAL_TABLE;


-- Task 14: Consume Stream Data

MERGE INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE AS T 
USING (
    SELECT 
        SS.ID ,
        SS.PRODUCT, 
        SS.PRICE ,
        SS.AMOUNT , 
        SS.STORE_ID ,
        ST.LOCATION , 
        ST.EMPLOYEES
        FROM STREAMS_DB.PUBLIC.SALES_STREAM AS SS
        INNER JOIN STREAMS_DB.PUBLIC.STORE_TABLE AS ST
        ON SS.STORE_ID = ST.STORE_ID
) AS S
ON T.ID = S.ID 

WHEN MATCHED THEN UPDATE SET 
    T.PRODUCT = S.PRODUCT, 
    T.PRICE  = S.PRICE,
    T.AMOUNT = S.AMOUNT ,
    T.STORE_ID = S.STORE_ID,
    T.LOCATION = S.LOCATION,
    T.EMPLOYEES = S.EMPLOYEES

WHEN NOT MATCHED THEN INSERT
(
    ID,
    PRODUCT, 
    PRICE,
    AMOUNT ,
    STORE_ID,
    LOCATION,
    EMPLOYEES
)
VALUES(
    S.ID,
    S.PRODUCT, 
    S.PRICE,
    S.AMOUNT ,
    S.STORE_ID,
    S.LOCATION,
    S.EMPLOYEES
);



-- Task 15: Verify Stream After Consumption

SELECT * FROM STREAMS_DB.PUBLIC.SALES_STREAM;

-- Task 16: Insert More Sales Records


INSERT INTO STREAMS_DB.PUBLIC.SALES_RAW_STAGING
VALUES 
    (8 , 'Paprika', 4.99 , 1, 2),
    (9 , 'Tomato' , 3.99 , 1, 2);

-- Task 17: Consume Second Stream Data

-- Consume the newly captured stream records and insert them into SALES_FINAL_TABLE.

MERGE INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE AS T 
USING (
    SELECT 
        SS.ID ,
        SS.PRODUCT, 
        SS.PRICE ,
        SS.AMOUNT , 
        SS.STORE_ID ,
        ST.LOCATION , 
        ST.EMPLOYEES
        FROM STREAMS_DB.PUBLIC.SALES_STREAM AS SS
        INNER JOIN STREAMS_DB.PUBLIC.STORE_TABLE AS ST
        ON SS.STORE_ID = ST.STORE_ID
) AS S
ON T.ID = S.ID 

WHEN MATCHED THEN UPDATE SET 
    T.PRODUCT = S.PRODUCT, 
    T.PRICE  = S.PRICE,
    T.AMOUNT = S.AMOUNT ,
    T.STORE_ID = S.STORE_ID,
    T.LOCATION = S.LOCATION,
    T.EMPLOYEES = S.EMPLOYEES

WHEN NOT MATCHED THEN INSERT
(
    ID,
    PRODUCT, 
    PRICE,
    AMOUNT ,
    STORE_ID,
    LOCATION,
    EMPLOYEES
)
VALUES(
    S.ID,
    S.PRODUCT, 
    S.PRICE,
    S.AMOUNT ,
    S.STORE_ID,
    S.LOCATION,
    S.EMPLOYEES
);


-- Task 18: Verify Final Insert Output


-- SALES_FINAL_TABLE;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_FINAL_TABLE order by id asc;

-- SALES_RAW_STAGING;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

SELECT * 
FROM STREAMS_DB.PUBLIC.SALES_STREAM;



-- Task 19: Check Existing Data Before Update
-- Display records from:
-- SALES_RAW_STAGING;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

-- SALES_STREAM;
SELECT * 
FROM STREAMS_DB.PUBLIC.SALES_STREAM;


-- Task 20: Perform First Update
-- Update the product name:
-- Banana
-- to:
-- Potato
-- in SALES_RAW_STAGING.


UPDATE STREAMS_DB.PUBLIC.SALES_RAW_STAGING 
SET PRODUCT = 'Potato' 
WHERE PRODUCT = 'Banana';



-- Task 21: Check Stream After Update

SELECT * 
FROM STREAMS_DB.PUBLIC.SALES_STREAM;

-- Task 22: Consume Update Using MERGE

MERGE INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE AS T 
USING (
  SELECT 
        SS.ID ,
        SS.PRODUCT, 
        SS.PRICE ,
        SS.AMOUNT , 
        SS.STORE_ID ,
        ST.LOCATION , 
        ST.EMPLOYEES ,
        SS.METADATA$ACTION , 
        SS.METADATA$ISUPDATE 
        FROM STREAMS_DB.PUBLIC.SALES_STREAM AS SS
        INNER JOIN STREAMS_DB.PUBLIC.STORE_TABLE AS ST
        ON SS.STORE_ID = ST.STORE_ID
) AS S
ON T.ID = S.ID 

WHEN MATCHED 
AND S.METADATA$ACTION = 'INSERT' 
AND S.METADATA$ISUPDATE = TRUE
THEN UPDATE SET 
    T.PRODUCT = S.PRODUCT, 
    T.PRICE  = S.PRICE,
    T.AMOUNT = S.AMOUNT ,
    T.STORE_ID = S.STORE_ID;

-- Task 23: Verify First Update
-- Display data from:

-- SALES_FINAL_TABLE;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_FINAL_TABLE order by id asc;

-- SALES_RAW_STAGING;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

-- SALES_STREAM
SELECT * 
FROM STREAMS_DB.PUBLIC.SALES_STREAM;


-- Task 24: Perform Second Update

-- Update the product name:
-- Apple
-- to:
-- Green apple
-- in SALES_RAW_STAGING.

UPDATE STREAMS_DB.PUBLIC.SALES_RAW_STAGING 
SET PRODUCT = 'Green apple' 
WHERE PRODUCT = 'Apple';



-- Task 25: Consume Second Update Using MERGE


MERGE INTO STREAMS_DB.PUBLIC.SALES_FINAL_TABLE AS T 
USING (
  SELECT 
        SS.ID ,
        SS.PRODUCT, 
        SS.PRICE ,
        SS.AMOUNT , 
        SS.STORE_ID ,
        ST.LOCATION , 
        ST.EMPLOYEES ,
        SS.METADATA$ACTION , 
        SS.METADATA$ISUPDATE 
        FROM STREAMS_DB.PUBLIC.SALES_STREAM AS SS
        INNER JOIN STREAMS_DB.PUBLIC.STORE_TABLE AS ST
        ON SS.STORE_ID = ST.STORE_ID
) AS S
ON T.ID = S.ID 

WHEN MATCHED 
AND S.METADATA$ACTION = 'INSERT' 
AND S.METADATA$ISUPDATE = TRUE
THEN UPDATE SET 
    T.PRODUCT = S.PRODUCT, 
    T.PRICE  = S.PRICE,
    T.AMOUNT = S.AMOUNT ,
    T.STORE_ID = S.STORE_ID;


-- Task 26: Verify Final Output


-- SALES_FINAL_TABLE;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_FINAL_TABLE order by id asc;

-- SALES_RAW_STAGING;
SELECT * FROM  STREAMS_DB.PUBLIC.SALES_RAW_STAGING;

-- SALES_STREAM
SELECT * 
FROM STREAMS_DB.PUBLIC.SALES_STREAM;